SELECT COMMENT_NO, COMMENT_CONTENT , COMMENT_DATE , BOARD_NO , BOARD_TITLE 
FROM "COMMENT" c
JOIN BOARD b USING(BOARD_NO)
WHERE c.MEMBER_NO = 16
;

SELECT COUNT(*) FROM "COMMENT"
	WHERE MEMBER_NO = 16